package com.example.loginsystem.service;

// =============================================================================
// AuthService.java — The Business Logic Layer
// =============================================================================
//
// WHAT IS THE SERVICE LAYER?
// ──────────────────────────
// The Service layer sits between the Controller (handles HTTP) and the
// Repository (handles database). It contains the BUSINESS LOGIC.
//
// WHY HAVE A SERVICE LAYER?
// ──────────────────────────
//   1. SEPARATION OF CONCERNS: Controllers handle HTTP stuff (parsing requests,
//      returning responses). Services handle what your app actually DOES.
//
//   2. REUSABILITY: Multiple controllers can call the same service method.
//
//   3. TESTABILITY: Service logic is easy to unit test (no HTTP involved).
//
//   4. TRANSACTION MANAGEMENT: Service methods run in DB transactions.
//      If one part fails, everything in that method rolls back.
//
// WHAT AuthService DOES:
//   • register(): validates input, hashes password, saves user, returns token
//   • login():    validates credentials, generates token, returns it
//   • getCurrentUser(): returns info about the logged-in user
//
// =============================================================================

import com.example.loginsystem.dto.AuthResponse;
import com.example.loginsystem.dto.LoginRequest;
import com.example.loginsystem.dto.RegisterRequest;
import com.example.loginsystem.entity.User;
import com.example.loginsystem.exception.InvalidCredentialsException;
import com.example.loginsystem.exception.UserAlreadyExistsException;
import com.example.loginsystem.repository.UserRepository;
import com.example.loginsystem.security.JwtUtil;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.AuthenticationException;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Set;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class AuthService {

    private static final Logger log = LoggerFactory.getLogger(AuthService.class);

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final AuthenticationManager authenticationManager;
    private final JwtUtil jwtUtil;

    // =========================================================================
    // REGISTRATION
    // =========================================================================

    /**
     * Register a new user.
     *
     * FLOW:
     *   1. Check if username/email already taken
     *   2. Hash the password (NEVER store plain text!)
     *   3. Build and save the User entity
     *   4. Generate a JWT token for the new user
     *   5. Return the token so the user is "instantly logged in"
     */
    @Transactional
    // @Transactional wraps the entire method in a database transaction.
    // If any line throws an exception, ALL database changes are rolled back.
    // Think of it like: either EVERYTHING succeeds or NOTHING is saved.
    public AuthResponse register(RegisterRequest request) {

        // --- Validation: check uniqueness ---
        // We check BOTH username and email before trying to save.
        // This gives a clear error message instead of a DB constraint violation.

        if (userRepository.existsByUsername(request.getUsername())) {
            throw new UserAlreadyExistsException(
                    "Username '" + request.getUsername() + "' is already taken");
        }

        if (userRepository.existsByEmail(request.getEmail())) {
            throw new UserAlreadyExistsException(
                    "Email '" + request.getEmail() + "' is already registered");
        }

        // --- Hash the password ---
        //
        // passwordEncoder.encode("mySecret123") might return:
        //   "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy"
        //
        // This is a BCrypt hash. It includes:
        //   $2a$    = BCrypt version
        //   $10$    = cost factor
        //   N9qo... = 22 chars random salt
        //   68LJZ.. = 31 chars hash
        //
        // The SAME password gives a DIFFERENT hash every time (random salt).
        // But BCryptPasswordEncoder.matches("mySecret123", storedHash) = true!

        String hashedPassword = passwordEncoder.encode(request.getPassword());

        // --- Build the User entity ---
        //
        // Using the @Builder pattern generated by Lombok.
        // This is much cleaner than calling setters on a new User().

        User user = User.builder()
                .username(request.getUsername())
                .email(request.getEmail())
                .password(hashedPassword) // HASHED, never plain text!
                .roles(Set.of(User.Role.ROLE_USER)) // Every new user gets ROLE_USER
                .active(true)
                .build();

        // --- Save to database ---
        // JPA's save() runs: INSERT INTO users (username, email, password, ...) VALUES (...)
        // After saving, user.getId() will have the auto-generated ID.
        User savedUser = userRepository.save(user);
        log.info("New user registered: {}", savedUser.getUsername());

        // --- Generate JWT token ---
        // We need UserDetails (Spring Security format) to generate the token.
        // Load it fresh from DB to get the full picture with authorities.
        UserDetails userDetails = org.springframework.security.core.userdetails.User
                .withUsername(savedUser.getUsername())
                .password(savedUser.getPassword())
                .authorities(savedUser.getRoles().stream()
                        .map(role -> new org.springframework.security.core.authority.SimpleGrantedAuthority(role.name()))
                        .collect(Collectors.toList()))
                .build();

        String token = jwtUtil.generateToken(userDetails);

        // --- Build and return the response ---
        return buildAuthResponse(token, savedUser);
    }

    // =========================================================================
    // LOGIN
    // =========================================================================

    /**
     * Authenticate an existing user and return a JWT token.
     *
     * FLOW:
     *   1. Ask AuthenticationManager to verify username + password
     *   2. If credentials are wrong → AuthenticationManager throws exception
     *   3. If correct → get the UserDetails from the Authentication object
     *   4. Generate JWT token
     *   5. Return token
     */
    public AuthResponse login(LoginRequest request) {

        try {
            // --- Authenticate ---
            //
            // UsernamePasswordAuthenticationToken is a container for credentials.
            // We create an "unauthenticated" token (not yet verified) and pass it
            // to AuthenticationManager for verification.
            //
            // INTERNALLY, AuthenticationManager:
            //   1. Calls CustomUserDetailsService.loadUserByUsername(username)
            //   2. Compares: BCrypt.matches(rawPassword, loadedUser.getPassword())
            //   3. If match → returns an authenticated Authentication object
            //   4. If no match → throws BadCredentialsException

            Authentication authentication = authenticationManager.authenticate(
                    new UsernamePasswordAuthenticationToken(
                            request.getUsername(),  // principal (the "who")
                            request.getPassword()   // credentials (the "proof")
                    )
            );

            // --- Extract UserDetails from the authenticated token ---
            // authentication.getPrincipal() returns the UserDetails object
            // that was loaded during authentication.
            UserDetails userDetails = (UserDetails) authentication.getPrincipal();

            // --- Generate JWT ---
            String token = jwtUtil.generateToken(userDetails);

            // --- Load the full User entity for the response ---
            User user = userRepository.findByUsername(userDetails.getUsername())
                    .orElseThrow(); // Already authenticated, so it must exist

            log.info("User logged in: {}", user.getUsername());

            return buildAuthResponse(token, user);

        } catch (AuthenticationException e) {
            // AuthenticationException covers:
            //   BadCredentialsException = wrong password
            //   UsernameNotFoundException = user doesn't exist
            //   DisabledException = account is disabled
            //   LockedException = account is locked
            //
            // SECURITY TIP: Don't distinguish between "wrong password" and
            // "user not found" in the error message — that leaks information
            // (an attacker can enumerate valid usernames by testing responses).
            // Generic "Invalid credentials" is best practice.
            log.warn("Failed login attempt for username: {}", request.getUsername());
            throw new InvalidCredentialsException("Invalid username or password");
        }
    }

    // =========================================================================
    // HELPER: Build AuthResponse from a User entity + token
    // =========================================================================

    private AuthResponse buildAuthResponse(String token, User user) {
        Set<String> roleNames = user.getRoles().stream()
                .map(User.Role::name) // enum → String: "ROLE_USER"
                .collect(Collectors.toSet());

        return AuthResponse.builder()
                .token(token)
                .tokenType("Bearer")
                .username(user.getUsername())
                .email(user.getEmail())
                .roles(roleNames)
                .build();
    }
}
